[package]
name = "offline-phragmen"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
async-std = "1.2.0"
url = "1.7.0"
log = "0.4.8"
env_logger = "0.7.1"
separator = "0.4.1"
hex = "0.4"
hex-literal = "0.2.1"
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee/", rev = "a0bea41c4f37125fa742ec48b12e11cf55c592b5", features = ["ws"] }
serde = { version = "1.0.102", features = ["derive"] }
serde_json = { version = "1.0" }
clap = { version = "2.33.0", features = ["yaml"] }
lazy_static = "1.4.0"

# Needed anyhow
node-primitives = { git = "https://github.com/paritytech/substrate", branch = "master" }
# node-runtime = { git = "https://github.com/paritytech/substrate", branch = "master" }
kusama-runtime = { git = "https://github.com/paritytech/polkadot/", branch = "master" }

# Remote crates
sc-rpc-api = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "master", features = ["std", "full_crypto"] }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-phragmen = { git = "https://github.com/paritytech/substrate", branch = "master" }
sp-io = { git = "https://github.com/paritytech/substrate", branch = "master" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "master" }
frame-system = { git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-staking = { git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-identity = { git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-indices = { git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-balances = { git = "https://github.com/paritytech/substrate", branch = "master" }
pallet-transaction-payment-rpc-runtime-api = { git = "https://github.com/paritytech/substrate", branch = "master" }

# For local debug
# sc-rpc-api = { path = "./../substrate/client/rpc-api" }
# sp-core = { path = "./../substrate/primitives/core" }
# sp-runtime = { path = "./../substrate/primitives/runtime" }
# sp-phragmen = { path = "./../substrate/primitives/phragmen" }
# sp-io = { path = "./../substrate/primitives/io" }
# frame-support = { path = "./../substrate/frame/support" }
# frame-system = { path = "./../substrate/frame/system" }
# pallet-staking = { path = "./../substrate/frame/staking" }
# pallet-identity = { path = "./../substrate/frame/identity" }
# pallet-indices = { path = "./../substrate/frame/indices" }
# node-runtime = { path = "./../substrate/bin/node/runtime" }
