[package]
name = "sub-storage"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
jsonrpsee = { version = "0.1.0", features = ["ws"] }

sp-core = { version = "2.0.0-rc6" }
sp-runtime = { version = "2.0.0-rc6" }
frame-support = { version = "2.0.0-rc6" }
sp-version = { version = "2.0.0-rc6" }
frame-metadata = { version = "11.0.0-rc6" }

# Optional for helpers only.
frame-system = { version = "2.0.0-rc6", optional = true }
pallet-identity = { version = "2.0.0-rc6", optional = true }
pallet-balances = { version = "2.0.0-rc6", optional = true }
ansi_term = { version = "0.12.1", optional = true }

[dev-dependencies]
async-std = { version = "1.6.2" }
hex-literal = "0.3.0"
frame-system = { version = "2.0.0-rc6" }
pallet-balances = { version = "2.0.0-rc6" }
pallet-staking = { version = "2.0.0-rc6" }

[features]
default = []
helpers = [
	"frame-system",
	"pallet-identity",
	"pallet-balances",
	"ansi_term",
]
