[package]
name = "sub-storage"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee/", rev = "a0bea41c4f37125fa742ec48b12e11cf55c592b5", features = ["ws"] }

node-primitives = { package = "polkadot-primitives", git = "https://github.com/paritytech/polkadot", branch = "offchain-phragmen-v0.7.33" }
sp-core = { git = "https://github.com/paritytech/substrate", rev = "e7457b1eb", features = ["std", "full_crypto"] }
frame-support = { git = "https://github.com/paritytech/substrate", rev = "e7457b1eb" }

[dev-dependencies]
async-std = "1.2.0"
hex-literal = "0.2.1"

kusama-runtime = { git = "https://github.com/paritytech/polkadot/", branch = "offchain-phragmen-v0.7.33" }

frame-system = { git = "https://github.com/paritytech/substrate", rev = "e7457b1eb" }
pallet-balances = { git = "https://github.com/paritytech/substrate", rev = "e7457b1eb" }
