[package]
name = "sub-storage"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
jsonrpsee = { version = "0.1.0", features = ["ws"] }

node-primitives = { package = "polkadot-primitives", git = "https://github.com/paritytech/polkadot", branch = "offline-phragmen-v0.8.11" }
sp-core = "2.0.0-rc4"
frame-support = "2.0.0-rc4"
frame-system = "2.0.0-rc4"
sp-version = "2.0.0-rc4"
frame-metadata = "11.0.0-rc4"

# Optional for helpers only.
pallet-identity = { version = "2.0.0-rc4", optional = true }
pallet-balances = { version = "2.0.0-rc4", optional = true }
ansi_term = { version = "0.12.1", optional = true }

[dev-dependencies]
async-std = { version = "1.5.0" }
hex-literal = "0.2.1"
frame-system = "2.0.0-rc4"
pallet-balances = "2.0.0-rc4"

[features]
default = []
helpers = [
	"pallet-identity",
	"pallet-balances",
	"ansi_term",
]
