[package]
name = "remote-externalities"
version = "0.1.0"
authors = ["kianenigma <kian.peymani@gmail.com>"]
edition = "2018"

[dependencies]
async-std = { version = "1.5.0" }
jsonrpsee = { version = "0.1.0", features = ["ws"] }
separator = "0.4.1"
ansi_term = "0.12.1"
env_logger = "0.7.1"
log = "0.4.8"

sub-storage = { path = "../sub-storage" }
sp-io = "2.0.0-rc4"
sp-core = "2.0.0-rc4"
sp-externalities = "0.8.0-rc4"

[dev-dependencies]
hex-literal = "0.2.1"
tokio-test = "0.2.1"
frame-system = "2.0.0-rc4"
frame-support = "2.0.0-rc4"
pallet-staking = "2.0.0-rc4"
sp-runtime = "2.0.0-rc4"
