[package]
name = "offline-election"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
# Only update after https://github.com/async-rs/async-std/pull/799 is merged.
async-std = { version = "1.2.0", features = ["attributes"] }
url = "2.1.1"
log = "0.4.8"
env_logger = "0.7.1"
separator = "0.4.1"
hex = "0.4"
hex-literal = "0.2.1"
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
jsonrpsee = { git = "https://github.com/paritytech/jsonrpsee/", rev = "a0bea41c4f37125fa742ec48b12e11cf55c592b5", features = ["ws"] }
serde = { version = "1.0.102", features = ["derive"] }
serde_json = { version = "1.0" }
lazy_static = "1.4.0"
atomic_refcell = "0.1.6"
ansi_term = "0.12.1"
structopt = { version = "0.3" }

sub-storage = { path = "../sub-storage", features = ["helpers"] }

# Dynamic stuff.. technically we should get these from the metadata.. For now we use our branch in
# lockstep with polkadot repo.
node-primitives = { package = "polkadot-primitives", git = "https://github.com/paritytech/polkadot", branch = "offline-phragmen-v0.8.11" }

# node-runtime = { path = "../substrate/bin/node/runtime" }

# This commit rev must come from the lock file of the associated version of kusama runtime above.
sc-rpc-api = { git = "https://github.com/paritytech/substrate", rev = "31c3e06ded197bdf28130ac0c5310283b2d1b5b3" }
sp-core = { git = "https://github.com/paritytech/substrate", rev = "31c3e06ded197bdf28130ac0c5310283b2d1b5b3" }
sp-io = { git = "https://github.com/paritytech/substrate", rev = "31c3e06ded197bdf28130ac0c5310283b2d1b5b3" }
sp-runtime = { git = "https://github.com/paritytech/substrate", rev = "31c3e06ded197bdf28130ac0c5310283b2d1b5b3" }
sp-npos-elections = { git = "https://github.com/paritytech/substrate", rev = "31c3e06ded197bdf28130ac0c5310283b2d1b5b3" }
frame-support = { git = "https://github.com/paritytech/substrate", rev = "31c3e06ded197bdf28130ac0c5310283b2d1b5b3" }
frame-system = { git = "https://github.com/paritytech/substrate", rev = "31c3e06ded197bdf28130ac0c5310283b2d1b5b3" }
pallet-staking = { git = "https://github.com/paritytech/substrate", rev = "31c3e06ded197bdf28130ac0c5310283b2d1b5b3" }

[dev-dependencies]
assert_cmd = "1.0.1"
