[package]
name = "offline-election"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
async-std = { version = "1.5.0", features = ["attributes"] }
jsonrpsee = { version = "0.1.0", features = ["ws"] }
url = "2.1.1"
log = "0.4.8"
env_logger = "0.7.1"
separator = "0.4.1"
hex = "0.4"
hex-literal = "0.2.1"
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false, features = ["derive"] }
serde = { version = "1.0.102", features = ["derive"] }
serde_json = { version = "1.0" }
lazy_static = "1.4.0"
atomic_refcell = "0.1.6"
ansi_term = "0.12.1"
structopt = { version = "0.3" }

sub-storage = { path = "../sub-storage", features = ["helpers"] }

sc-rpc-api = "0.8.0-rc4"
sp-core = "2.0.0-rc4"
sp-io = "2.0.0-rc4"
sp-runtime = "2.0.0-rc4"
sp-npos-elections = "2.0.0-rc4"
frame-support = "2.0.0-rc4"
frame-system = "2.0.0-rc4"
pallet-staking = "2.0.0-rc4"

[dev-dependencies]
assert_cmd = "1.0.1"
